-- ============================================================================
-- Per-event Additional Info settings: audio recording / age category /
-- participant-submitted YouTube tracks / participant-submitted team members.
--
-- Run this ENTIRE script, top to bottom, in WKSP_GCODE2 SQL Workshop on the
-- cloud ADB (the ATHARVA MCP connection has no CREATE/ALTER privilege there,
-- so this cannot be run programmatically from the assistant session).
--
-- Already run and verified end-to-end against the local dev DB
-- (localhost:1521/FREEPDB1) before being consolidated here. Take a backup /
-- snapshot of WKSP_GCODE2 before running against prod, per normal process.
--
-- Order matters: tables first (new columns must exist before the packages
-- that reference them will compile), then packages, then ORDS routes.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. TABLES
-- ----------------------------------------------------------------------------

ALTER TABLE EVENTS ADD (
  AUDIO_RECORDING_ENABLED   NUMBER(1,0) DEFAULT 1 NOT NULL,
  AGE_CATEGORY_REQUIREMENT  VARCHAR2(20) DEFAULT 'OPTIONAL' NOT NULL,
  TRACK_SUBMISSION_ENABLED  NUMBER(1,0) DEFAULT 0 NOT NULL,
  MEMBER_NAMES_ENABLED      NUMBER(1,0) DEFAULT 0 NOT NULL
);

ALTER TABLE EVENTS ADD CONSTRAINT CK_EVENTS_AUDIO_RECORDING_ENABLED
  CHECK (AUDIO_RECORDING_ENABLED IN (0,1));
ALTER TABLE EVENTS ADD CONSTRAINT CK_EVENTS_AGE_CATEGORY_REQUIREMENT
  CHECK (AGE_CATEGORY_REQUIREMENT IN ('OFF','OPTIONAL','REQUIRED'));
ALTER TABLE EVENTS ADD CONSTRAINT CK_EVENTS_TRACK_SUBMISSION_ENABLED
  CHECK (TRACK_SUBMISSION_ENABLED IN (0,1));
ALTER TABLE EVENTS ADD CONSTRAINT CK_EVENTS_MEMBER_NAMES_ENABLED
  CHECK (MEMBER_NAMES_ENABLED IN (0,1));

-- AUDIO_RECORDING_ENABLED=1 / AGE_CATEGORY_REQUIREMENT='OPTIONAL' preserve
-- today's unconditional-ask behavior for every existing event row.
-- TRACK_SUBMISSION_ENABLED=0 / MEMBER_NAMES_ENABLED=0 default off — brand
-- new, opt-in features with no prior behavior to preserve.

-- Participant-submitted, not organizer-authored — same ownership as the
-- existing audio submission. FK to the participant, not the event.

CREATE TABLE PARTICIPANT_YOUTUBE_TRACKS (
  ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
  PARTICIPANT_ID NUMBER NOT NULL,
  TRACK_NAME     VARCHAR2(200) NOT NULL,
  YOUTUBE_URL    VARCHAR2(1000) NOT NULL,
  SORT_ORDER     NUMBER DEFAULT 0,
  CONSTRAINT PK_PARTICIPANT_YOUTUBE_TRACKS PRIMARY KEY (ID),
  CONSTRAINT FK_YOUTUBE_TRACKS_PARTICIPANT FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES GCODE_EVENT_PARTICIPANTS(ID) ON DELETE CASCADE
);

CREATE TABLE PARTICIPANT_TEAM_MEMBERS (
  ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
  PARTICIPANT_ID NUMBER NOT NULL,
  MEMBER_NAME    VARCHAR2(200) NOT NULL,
  SORT_ORDER     NUMBER DEFAULT 0,
  CONSTRAINT PK_PARTICIPANT_TEAM_MEMBERS PRIMARY KEY (ID),
  CONSTRAINT FK_TEAM_MEMBERS_PARTICIPANT FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES GCODE_EVENT_PARTICIPANTS(ID) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- 2. PACKAGE: GCODE_EVENTS_API (spec, then body)
-- ----------------------------------------------------------------------------

CREATE OR REPLACE
PACKAGE gcode_events_api AS

  FUNCTION default_status_id
    RETURN events.status_id%TYPE;

  PROCEDURE create_event (
    p_title                         IN events.title%TYPE,
    p_event_type_id                 IN events.event_type_id%TYPE,
    p_mode_of_event_id              IN events.mode_of_event_id%TYPE,
    p_status_id                     IN events.status_id%TYPE DEFAULT NULL,
    p_summary                       IN events.summary%TYPE DEFAULT NULL,
    p_description                   IN events.description%TYPE DEFAULT NULL,
    p_start_date                    IN events.start_date%TYPE DEFAULT NULL,
    p_end_date                      IN events.end_date%TYPE DEFAULT NULL,
    p_registration_start            IN events.registration_start%TYPE DEFAULT NULL,
    p_registration_deadline         IN events.registration_deadline%TYPE DEFAULT NULL,
    p_city                          IN events.city%TYPE DEFAULT NULL,
    p_venue_address                 IN events.venue_address%TYPE DEFAULT NULL,
    p_participation_link            IN events.participation_link%TYPE DEFAULT NULL,
    p_max_attendees                 IN events.max_attendees%TYPE DEFAULT NULL,
    p_ticket_price                  IN events.ticket_price%TYPE DEFAULT 0,
    p_is_featured                   IN events.is_featured%TYPE DEFAULT 0,
    p_certificate_offered           IN events.certificate_offered%TYPE DEFAULT 0,
    p_cover_image_url               IN events.cover_image_url%TYPE DEFAULT NULL,
    p_banner_image_url              IN events.banner_image_url%TYPE DEFAULT NULL,
    p_is_external                   IN events.is_external%TYPE DEFAULT 0,
    p_external_url                  IN events.external_url%TYPE DEFAULT NULL,
    p_created_by                    IN events.created_by%TYPE DEFAULT NULL,
    p_organizer_id                  IN events.organizer_id%TYPE DEFAULT NULL,
    p_max_tickets_per_registration  IN events.max_tickets_per_registration%TYPE DEFAULT NULL,
    p_terms                         IN events.terms%TYPE DEFAULT NULL,
    p_eligibility                   IN events.eligibility%TYPE DEFAULT NULL,
    p_duration_text                 IN events.duration_text%TYPE DEFAULT NULL,

    p_attendee_label                   IN events.attendee_label%TYPE DEFAULT NULL,
    p_attendee_description             IN events.attendee_description%TYPE DEFAULT NULL,
    p_attendee_registration_enabled    IN events.attendee_registration_enabled%TYPE DEFAULT 1,
    p_participant_registration_enabled IN events.participant_registration_enabled%TYPE DEFAULT 0,
    p_participant_label                IN events.participant_label%TYPE DEFAULT NULL,
    p_participant_description          IN events.participant_description%TYPE DEFAULT NULL,
    p_participant_price                IN events.participant_price%TYPE DEFAULT NULL,
    p_participant_capacity             IN events.participant_capacity%TYPE DEFAULT NULL,
    p_participant_max_tickets_per_registration IN events.participant_max_tickets_per_registration%TYPE DEFAULT NULL,
    p_participant_registration_start    IN events.participant_registration_start%TYPE DEFAULT NULL,
    p_participant_registration_deadline IN events.participant_registration_deadline%TYPE DEFAULT NULL,
    p_audio_recording_enabled           IN events.audio_recording_enabled%TYPE DEFAULT 1,
    p_age_category_requirement          IN events.age_category_requirement%TYPE DEFAULT 'OPTIONAL',
    p_track_submission_enabled          IN events.track_submission_enabled%TYPE DEFAULT 0,
    p_member_names_enabled              IN events.member_names_enabled%TYPE DEFAULT 0,

    p_id OUT events.id%TYPE
  );

  PROCEDURE update_event (
    p_id                            IN events.id%TYPE,
    p_title                         IN events.title%TYPE DEFAULT NULL,
    p_event_type_id                 IN events.event_type_id%TYPE DEFAULT NULL,
    p_mode_of_event_id              IN events.mode_of_event_id%TYPE DEFAULT NULL,
    p_status_id                     IN events.status_id%TYPE DEFAULT NULL,
    p_summary                       IN events.summary%TYPE DEFAULT NULL,
    p_description                   IN events.description%TYPE DEFAULT NULL,
    p_start_date                    IN events.start_date%TYPE DEFAULT NULL,
    p_end_date                      IN events.end_date%TYPE DEFAULT NULL,
    p_registration_start            IN events.registration_start%TYPE DEFAULT NULL,
    p_registration_deadline         IN events.registration_deadline%TYPE DEFAULT NULL,
    p_city                          IN events.city%TYPE DEFAULT NULL,
    p_venue_address                 IN events.venue_address%TYPE DEFAULT NULL,
    p_participation_link            IN events.participation_link%TYPE DEFAULT NULL,
    p_max_attendees                 IN events.max_attendees%TYPE DEFAULT NULL,
    p_ticket_price                  IN events.ticket_price%TYPE DEFAULT NULL,
    p_is_featured                   IN events.is_featured%TYPE DEFAULT NULL,
    p_certificate_offered           IN events.certificate_offered%TYPE DEFAULT NULL,
    p_cover_image_url               IN events.cover_image_url%TYPE DEFAULT NULL,
    p_banner_image_url              IN events.banner_image_url%TYPE DEFAULT NULL,
    p_is_external                   IN events.is_external%TYPE DEFAULT NULL,
    p_external_url                  IN events.external_url%TYPE DEFAULT NULL,
    p_updated_by                    IN events.updated_by%TYPE DEFAULT NULL,
    p_organizer_id                  IN events.organizer_id%TYPE DEFAULT NULL,
    p_max_tickets_per_registration  IN events.max_tickets_per_registration%TYPE DEFAULT NULL,
    p_terms                         IN events.terms%TYPE DEFAULT NULL,
    p_eligibility                   IN events.eligibility%TYPE DEFAULT NULL,
    p_duration_text                 IN events.duration_text%TYPE DEFAULT NULL,
    p_attendee_label                   IN events.attendee_label%TYPE DEFAULT NULL,
    p_attendee_description             IN events.attendee_description%TYPE DEFAULT NULL,
    p_attendee_registration_enabled    IN events.attendee_registration_enabled%TYPE DEFAULT NULL,
    p_participant_registration_enabled IN events.participant_registration_enabled%TYPE DEFAULT NULL,
    p_participant_label                IN events.participant_label%TYPE DEFAULT NULL,
    p_participant_description          IN events.participant_description%TYPE DEFAULT NULL,
    p_participant_price                IN events.participant_price%TYPE DEFAULT NULL,
    p_participant_capacity             IN events.participant_capacity%TYPE DEFAULT NULL,
    p_participant_max_tickets_per_registration IN events.participant_max_tickets_per_registration%TYPE DEFAULT NULL,
    p_participant_registration_start    IN events.participant_registration_start%TYPE DEFAULT NULL,
    p_participant_registration_deadline IN events.participant_registration_deadline%TYPE DEFAULT NULL,
    p_rating_mode IN events.rating_mode%TYPE DEFAULT NULL,
    p_audio_recording_enabled           IN events.audio_recording_enabled%TYPE DEFAULT NULL,
    p_age_category_requirement          IN events.age_category_requirement%TYPE DEFAULT NULL,
    p_track_submission_enabled          IN events.track_submission_enabled%TYPE DEFAULT NULL,
    p_member_names_enabled              IN events.member_names_enabled%TYPE DEFAULT NULL
  );

  PROCEDURE delete_event (
    p_id IN events.id%TYPE
  );

  PROCEDURE get_event (
    p_id     IN events.id%TYPE,
    p_result OUT SYS_REFCURSOR
  );

  PROCEDURE replace_timeline (
    p_event_id IN events.id%TYPE,
    p_items    IN CLOB
  );

  PROCEDURE replace_social_links (
    p_event_id IN events.id%TYPE,
    p_items    IN CLOB
  );

  PROCEDURE replace_media (
    p_event_id IN events.id%TYPE,
    p_items    IN CLOB
  );

  PROCEDURE assign_category (
    p_event_id    IN events.id%TYPE,
    p_category_id IN event_categories.id%TYPE
  );

  PROCEDURE remove_category (
    p_event_id    IN events.id%TYPE,
    p_category_id IN event_categories.id%TYPE
  );

  PROCEDURE set_cover_image (
    p_id  IN events.id%TYPE,
    p_url IN events.cover_image_url%TYPE
  );

  PROCEDURE set_banner_image (
    p_id  IN events.id%TYPE,
    p_url IN events.banner_image_url%TYPE
  );

END gcode_events_api;
/


CREATE OR REPLACE
PACKAGE BODY gcode_events_api AS

  FUNCTION default_status_id RETURN events.status_id%TYPE IS
    v_id event_status.id%TYPE;
  BEGIN
    SELECT id INTO v_id FROM event_status WHERE status_code = 'DRAFT';
    RETURN v_id;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL;
  END default_status_id;

  PROCEDURE create_event (
    p_title                       IN  events.title%TYPE,
    p_event_type_id               IN  events.event_type_id%TYPE,
    p_mode_of_event_id            IN  events.mode_of_event_id%TYPE,
    p_status_id                   IN  events.status_id%TYPE            DEFAULT NULL,
    p_summary                     IN  events.summary%TYPE              DEFAULT NULL,
    p_description                 IN  events.description%TYPE          DEFAULT NULL,
    p_start_date                  IN  events.start_date%TYPE           DEFAULT NULL,
    p_end_date                    IN  events.end_date%TYPE             DEFAULT NULL,
    p_registration_start          IN  events.registration_start%TYPE   DEFAULT NULL,
    p_registration_deadline       IN  events.registration_deadline%TYPE DEFAULT NULL,
    p_city                        IN  events.city%TYPE                 DEFAULT NULL,
    p_venue_address               IN  events.venue_address%TYPE        DEFAULT NULL,
    p_participation_link          IN  events.participation_link%TYPE   DEFAULT NULL,
    p_max_attendees               IN  events.max_attendees%TYPE        DEFAULT NULL,
    p_ticket_price                IN  events.ticket_price%TYPE         DEFAULT 0,
    p_is_featured                 IN  events.is_featured%TYPE          DEFAULT 0,
    p_certificate_offered         IN  events.certificate_offered%TYPE  DEFAULT 0,
    p_cover_image_url             IN  events.cover_image_url%TYPE      DEFAULT NULL,
    p_banner_image_url            IN  events.banner_image_url%TYPE     DEFAULT NULL,
    p_is_external                 IN  events.is_external%TYPE          DEFAULT 0,
    p_external_url                IN  events.external_url%TYPE         DEFAULT NULL,
    p_created_by                  IN  events.created_by%TYPE           DEFAULT NULL,
    p_organizer_id                IN  events.organizer_id%TYPE         DEFAULT NULL,
    p_max_tickets_per_registration IN events.max_tickets_per_registration%TYPE DEFAULT NULL,
    p_terms                      IN  events.terms%TYPE                DEFAULT NULL,
    p_eligibility                IN  events.eligibility%TYPE          DEFAULT NULL,
    p_duration_text               IN  events.duration_text%TYPE        DEFAULT NULL,
    p_attendee_label                   IN events.attendee_label%TYPE                   DEFAULT NULL,
    p_attendee_description             IN events.attendee_description%TYPE             DEFAULT NULL,
    p_attendee_registration_enabled    IN events.attendee_registration_enabled%TYPE    DEFAULT 1,
    p_participant_registration_enabled IN events.participant_registration_enabled%TYPE DEFAULT 0,
    p_participant_label                IN events.participant_label%TYPE                DEFAULT NULL,
    p_participant_description          IN events.participant_description%TYPE          DEFAULT NULL,
    p_participant_price                IN events.participant_price%TYPE                DEFAULT NULL,
    p_participant_capacity             IN events.participant_capacity%TYPE             DEFAULT NULL,
    p_participant_max_tickets_per_registration IN events.participant_max_tickets_per_registration%TYPE DEFAULT NULL,
    p_participant_registration_start    IN events.participant_registration_start%TYPE DEFAULT NULL,
    p_participant_registration_deadline IN events.participant_registration_deadline%TYPE DEFAULT NULL,
    p_audio_recording_enabled     IN events.audio_recording_enabled%TYPE DEFAULT 1,
    p_age_category_requirement    IN events.age_category_requirement%TYPE DEFAULT 'OPTIONAL',
    p_track_submission_enabled    IN events.track_submission_enabled%TYPE DEFAULT 0,
    p_member_names_enabled        IN events.member_names_enabled%TYPE DEFAULT 0,
    p_id                          OUT events.id%TYPE
  ) IS
    v_status_id events.status_id%TYPE;
  BEGIN
    v_status_id := NVL(p_status_id, default_status_id());

    INSERT INTO events (
      title, event_type_id, mode_of_event_id, status_id, summary, description,
      start_date, end_date, registration_start, registration_deadline, city, venue_address,
      participation_link, max_attendees, ticket_price, is_featured,
      certificate_offered, cover_image_url, banner_image_url, is_external,
      external_url, created_by, organizer_id, max_tickets_per_registration,
      terms, eligibility, duration_text, created_on,
      attendee_label, attendee_description, attendee_registration_enabled,
      participant_registration_enabled,
      participant_label, participant_description, participant_price, participant_capacity,
      participant_max_tickets_per_registration, participant_registration_start,
      participant_registration_deadline, audio_recording_enabled, age_category_requirement,
      track_submission_enabled, member_names_enabled
    ) VALUES (
      p_title, p_event_type_id, p_mode_of_event_id,
      v_status_id, p_summary, p_description,
      p_start_date, p_end_date, p_registration_start, p_registration_deadline, p_city, p_venue_address,
      p_participation_link, p_max_attendees, NVL(p_ticket_price,0),
      NVL(p_is_featured,0), NVL(p_certificate_offered,0), p_cover_image_url,
      p_banner_image_url, NVL(p_is_external,0), p_external_url, p_created_by,
      p_organizer_id, p_max_tickets_per_registration, p_terms, p_eligibility,
      p_duration_text, SYSTIMESTAMP,
      p_attendee_label, p_attendee_description, NVL(p_attendee_registration_enabled,1),
      NVL(p_participant_registration_enabled,0),
      p_participant_label, p_participant_description, p_participant_price, p_participant_capacity,
      p_participant_max_tickets_per_registration, p_participant_registration_start,
      p_participant_registration_deadline, NVL(p_audio_recording_enabled,1), NVL(p_age_category_requirement,'OPTIONAL'),
      NVL(p_track_submission_enabled,0), NVL(p_member_names_enabled,0)
    ) RETURNING id INTO p_id;
  END create_event;


    PROCEDURE update_event (
        p_id                          IN  events.id%TYPE,
        p_title                       IN  events.title%TYPE                DEFAULT NULL,
        p_event_type_id               IN  events.event_type_id%TYPE        DEFAULT NULL,
        p_mode_of_event_id            IN  events.mode_of_event_id%TYPE     DEFAULT NULL,
        p_status_id                   IN  events.status_id%TYPE            DEFAULT NULL,
        p_summary                     IN  events.summary%TYPE              DEFAULT NULL,
        p_description                 IN  events.description%TYPE          DEFAULT NULL,
        p_start_date                  IN  events.start_date%TYPE           DEFAULT NULL,
        p_end_date                    IN  events.end_date%TYPE             DEFAULT NULL,
        p_registration_start          IN  events.registration_start%TYPE   DEFAULT NULL,
        p_registration_deadline       IN  events.registration_deadline%TYPE DEFAULT NULL,
        p_city                        IN  events.city%TYPE                 DEFAULT NULL,
        p_venue_address               IN  events.venue_address%TYPE        DEFAULT NULL,
        p_participation_link          IN  events.participation_link%TYPE   DEFAULT NULL,
        p_max_attendees               IN  events.max_attendees%TYPE        DEFAULT NULL,
        p_ticket_price                IN  events.ticket_price%TYPE         DEFAULT NULL,
        p_is_featured                 IN  events.is_featured%TYPE          DEFAULT NULL,
        p_certificate_offered         IN  events.certificate_offered%TYPE  DEFAULT NULL,
        p_cover_image_url             IN  events.cover_image_url%TYPE      DEFAULT NULL,
        p_banner_image_url            IN  events.banner_image_url%TYPE     DEFAULT NULL,
        p_is_external                 IN  events.is_external%TYPE          DEFAULT NULL,
        p_external_url                IN  events.external_url%TYPE         DEFAULT NULL,
        p_updated_by                  IN  events.updated_by%TYPE           DEFAULT NULL,
        p_organizer_id                IN  events.organizer_id%TYPE         DEFAULT NULL,
        p_max_tickets_per_registration IN events.max_tickets_per_registration%TYPE DEFAULT NULL,
        p_terms                      IN  events.terms%TYPE                DEFAULT NULL,
        p_eligibility                IN  events.eligibility%TYPE          DEFAULT NULL,
        p_duration_text               IN  events.duration_text%TYPE        DEFAULT NULL,
        p_attendee_label                   IN events.attendee_label%TYPE                   DEFAULT NULL,
        p_attendee_description             IN events.attendee_description%TYPE             DEFAULT NULL,
        p_attendee_registration_enabled    IN events.attendee_registration_enabled%TYPE    DEFAULT NULL,
        p_participant_registration_enabled IN events.participant_registration_enabled%TYPE DEFAULT NULL,
        p_participant_label                IN events.participant_label%TYPE                DEFAULT NULL,
        p_participant_description          IN events.participant_description%TYPE          DEFAULT NULL,
        p_participant_price                IN events.participant_price%TYPE                DEFAULT NULL,
        p_participant_capacity             IN events.participant_capacity%TYPE             DEFAULT NULL,
        p_participant_max_tickets_per_registration IN events.participant_max_tickets_per_registration%TYPE DEFAULT NULL,
        p_participant_registration_start    IN events.participant_registration_start%TYPE DEFAULT NULL,
        p_participant_registration_deadline IN events.participant_registration_deadline%TYPE DEFAULT NULL,
        p_rating_mode                       IN events.rating_mode%TYPE DEFAULT NULL,
        p_audio_recording_enabled           IN events.audio_recording_enabled%TYPE DEFAULT NULL,
        p_age_category_requirement          IN events.age_category_requirement%TYPE DEFAULT NULL,
        p_track_submission_enabled          IN events.track_submission_enabled%TYPE DEFAULT NULL,
        p_member_names_enabled              IN events.member_names_enabled%TYPE DEFAULT NULL
  ) IS
  BEGIN
    UPDATE events SET
      title                        = NVL(p_title, title),
      event_type_id                = NVL(p_event_type_id, event_type_id),
      mode_of_event_id             = NVL(p_mode_of_event_id, mode_of_event_id),
      status_id                    = NVL(p_status_id, status_id),
      summary                      = NVL(p_summary, summary),
      description                  = NVL(p_description, description),
      start_date                   = NVL(p_start_date, start_date),
      end_date                     = NVL(p_end_date, end_date),
      registration_start           = NVL(p_registration_start, registration_start),
      registration_deadline        = NVL(p_registration_deadline, registration_deadline),
      city                         = NVL(p_city, city),
      venue_address                = NVL(p_venue_address, venue_address),
      participation_link           = NVL(p_participation_link, participation_link),
      max_attendees                = NVL(p_max_attendees, max_attendees),
      ticket_price                 = NVL(p_ticket_price, ticket_price),
      is_featured                  = NVL(p_is_featured, is_featured),
      certificate_offered          = NVL(p_certificate_offered, certificate_offered),
      cover_image_url              = NVL(p_cover_image_url, cover_image_url),
      banner_image_url             = NVL(p_banner_image_url, banner_image_url),
      is_external                  = NVL(p_is_external, is_external),
      external_url                 = NVL(p_external_url, external_url),
      organizer_id                 = NVL(p_organizer_id, organizer_id),
      max_tickets_per_registration = NVL(p_max_tickets_per_registration, max_tickets_per_registration),
      terms                        = NVL(p_terms, terms),
      eligibility                  = NVL(p_eligibility, eligibility),
      duration_text                = NVL(p_duration_text, duration_text),
      attendee_label                     = NVL(p_attendee_label, attendee_label),
      attendee_description               = NVL(p_attendee_description, attendee_description),
      attendee_registration_enabled      = NVL(p_attendee_registration_enabled, attendee_registration_enabled),
      participant_registration_enabled   = NVL(p_participant_registration_enabled, participant_registration_enabled),
      participant_label                  = NVL(p_participant_label, participant_label),
      participant_description            = NVL(p_participant_description, participant_description),
      participant_price                  = NVL(p_participant_price, participant_price),
      participant_capacity               = NVL(p_participant_capacity, participant_capacity),
      participant_max_tickets_per_registration = NVL(p_participant_max_tickets_per_registration, participant_max_tickets_per_registration),
      participant_registration_start     = NVL(p_participant_registration_start, participant_registration_start),
      participant_registration_deadline  = NVL(p_participant_registration_deadline, participant_registration_deadline),
      rating_mode                  = NVL(p_rating_mode, rating_mode),
      audio_recording_enabled      = NVL(p_audio_recording_enabled, audio_recording_enabled),
      age_category_requirement     = NVL(p_age_category_requirement, age_category_requirement),
      track_submission_enabled     = NVL(p_track_submission_enabled, track_submission_enabled),
      member_names_enabled         = NVL(p_member_names_enabled, member_names_enabled),
      updated_by                   = p_updated_by,
      updated_on                   = SYSTIMESTAMP
    WHERE id = p_id;
  END update_event;


  PROCEDURE delete_event (p_id IN events.id%TYPE) IS
      BEGIN
        DELETE FROM events WHERE id = p_id;
  END delete_event;

  PROCEDURE get_event (p_id IN events.id%TYPE, p_result OUT SYS_REFCURSOR) IS
BEGIN
  OPEN p_result FOR
    SELECT e.id                            AS "id",
           e.title                         AS "event_name",
           e.event_type_id                 AS "event_type_id",
           e.mode_of_event_id              AS "mode_of_event_id",
           e.status_id                     AS "status_id",
           e.summary                       AS "summary",
           e.description                   AS "description",
           e.start_date                    AS "start_date",
           e.end_date                      AS "end_date",
           e.registration_start            AS "registration_start",
           e.registration_deadline         AS "registration_deadline",
           e.city                          AS "city",
           e.venue_address                 AS "address",
           e.participation_link            AS "participation_link",
           e.max_attendees                 AS "max_attendees",
           e.ticket_price                  AS "ticket_price",
           e.is_featured                   AS "is_featured",
           e.certificate_offered           AS "certificate_offered",
           e.cover_image_url               AS "cover_image_url",
           e.banner_image_url              AS "banner_image_url",
           e.is_external                   AS "is_external",
           e.external_url                  AS "external_url",
           e.created_by                    AS "created_by",
           e.created_on                    AS "created_on",
           e.updated_by                    AS "updated_by",
           e.updated_on                    AS "updated_on",
          TO_CHAR(e.organizer_id)                AS "organizer_id",
           e.max_tickets_per_registration  AS "max_tickets_per_registration",
           e.duration_text                 AS "duration_text",
           e.rating_mode                   AS "rating_mode",
           e.audio_recording_enabled       AS "audio_recording_enabled",
           e.age_category_requirement      AS "age_category_requirement",
           e.track_submission_enabled      AS "track_submission_enabled",
           e.member_names_enabled          AS "member_names_enabled",
           e.terms                         AS "terms",
           e.eligibility                   AS "eligibility",
           e.attendee_label                    AS "attendee_label",
           e.attendee_description              AS "attendee_description",
           e.attendee_registration_enabled     AS "attendee_registration_enabled",
           e.participant_registration_enabled  AS "participant_registration_enabled",
           e.participant_label                 AS "participant_label",
           e.participant_description           AS "participant_description",
           e.participant_price                 AS "participant_price",
           e.participant_capacity              AS "participant_capacity",
           e.participant_max_tickets_per_registration AS "participant_max_tickets_per_registration",
           e.participant_registration_start    AS "participant_registration_start",
           e.participant_registration_deadline AS "participant_registration_deadline",
           (SELECT NVL(SUM(gep.quantity),0) FROM gcode_event_participants gep
            WHERE gep.event_id = e.id AND gep.active = 'Y'
              AND gep.category = 'PARTICIPANT') AS "participant_registered_count",
           gu.full_name                    AS "organizer_name",
           gu.email                        AS "organizer_email",
           et.name                         AS "type_name",
           m.mode_name                     AS "mode_name",
           s.status_code                   AS "status_code",
           (SELECT NVL(SUM(gep.quantity),0) FROM gcode_event_participants gep
            WHERE gep.event_id = e.id AND gep.active = 'Y'
              AND gep.category = 'ATTENDEE') AS "registered_count",
           (SELECT JSON_ARRAYAGG(ecm.category_id)
            FROM event_category_map ecm WHERE ecm.event_id = e.id) AS "category_ids",
           (SELECT JSON_ARRAYAGG(ec.category_name)
            FROM event_category_map ecm
            JOIN event_categories ec ON ec.id = ecm.category_id
            WHERE ecm.event_id = e.id) AS "category_names"
    FROM events e
    JOIN event_types    et ON et.id = e.event_type_id
    JOIN mode_of_events m  ON m.id  = e.mode_of_event_id
    JOIN event_status   s  ON s.id  = e.status_id
    LEFT JOIN gcode_users gu ON gu.user_id = e.organizer_id
    WHERE e.id = p_id;
END get_event;


  PROCEDURE replace_timeline (p_event_id IN events.id%TYPE, p_items IN CLOB) IS
  BEGIN
    DELETE FROM event_timeline WHERE event_id = p_event_id;
    INSERT INTO event_timeline (event_id, title, description, start_time, end_time, location, sort_order)
    SELECT p_event_id, j.title, j.description, j.start_time, j.end_time, j.location, j.sort_order
    FROM JSON_TABLE(p_items, '$[*]' COLUMNS (
      title       VARCHAR2(200)            PATH '$.title',
      description VARCHAR2(1000)           PATH '$.description',
      start_time  TIMESTAMP WITH TIME ZONE PATH '$.startTime',
      end_time    TIMESTAMP WITH TIME ZONE PATH '$.endTime',
      location    VARCHAR2(400)            PATH '$.location',
      sort_order  NUMBER                   PATH '$.sortOrder'
    )) j;
  END replace_timeline;

  PROCEDURE replace_social_links (p_event_id IN events.id%TYPE, p_items IN CLOB) IS
  BEGIN
    DELETE FROM event_social_links WHERE event_id = p_event_id;
    INSERT INTO event_social_links (event_id, platform, url)
    SELECT p_event_id, j.platform, j.url
    FROM JSON_TABLE(p_items, '$[*]' COLUMNS (
      platform VARCHAR2(60)   PATH '$.platform',
      url      VARCHAR2(1000) PATH '$.url'
    )) j;
  END replace_social_links;

  PROCEDURE replace_media (p_event_id IN events.id%TYPE, p_items IN CLOB) IS
  BEGIN
    DELETE FROM event_media WHERE event_id = p_event_id;
    INSERT INTO event_media (event_id, url, sort_order)
    SELECT p_event_id, j.url, j.sort_order
    FROM JSON_TABLE(p_items, '$[*]' COLUMNS (
      url        VARCHAR2(1000) PATH '$.url',
      sort_order NUMBER         PATH '$.sortOrder'
    )) j;
  END replace_media;

  PROCEDURE assign_category (p_event_id IN events.id%TYPE, p_category_id IN event_categories.id%TYPE) IS
  BEGIN
    MERGE INTO event_category_map t
    USING (SELECT p_event_id AS eid, p_category_id AS cid FROM dual) s
    ON (t.event_id = s.eid AND t.category_id = s.cid)
    WHEN NOT MATCHED THEN INSERT (event_id, category_id) VALUES (s.eid, s.cid);
  END assign_category;

  PROCEDURE remove_category (p_event_id IN events.id%TYPE, p_category_id IN event_categories.id%TYPE) IS
  BEGIN
    DELETE FROM event_category_map WHERE event_id = p_event_id AND category_id = p_category_id;
  END remove_category;

  PROCEDURE set_cover_image (p_id IN events.id%TYPE, p_url IN events.cover_image_url%TYPE) IS
  BEGIN
    UPDATE events SET cover_image_url = p_url, updated_on = SYSTIMESTAMP WHERE id = p_id;
  END set_cover_image;

  PROCEDURE set_banner_image (p_id IN events.id%TYPE, p_url IN events.banner_image_url%TYPE) IS
  BEGIN
    UPDATE events SET banner_image_url = p_url, updated_on = SYSTIMESTAMP WHERE id = p_id;
  END set_banner_image;

END gcode_events_api;
/


-- ----------------------------------------------------------------------------
-- 3. PACKAGE: GCODE_EVENT_PARTICIPANTS_API (spec, then body)
-- ----------------------------------------------------------------------------

CREATE OR REPLACE
PACKAGE gcode_event_participants_api AS

  PROCEDURE create_participant(
    p_event_id  IN  NUMBER,
    p_email     IN  VARCHAR2  DEFAULT NULL,
    p_full_name IN  VARCHAR2  DEFAULT NULL,
    p_quantity  IN  NUMBER    DEFAULT 1,
    p_status    IN  VARCHAR2  DEFAULT 'PENDING',
    p_active    IN  VARCHAR2  DEFAULT 'Y',
    p_category  IN  VARCHAR2  DEFAULT 'ATTENDEE',
    p_phone     IN  VARCHAR2  DEFAULT NULL,
    p_user_id   IN  NUMBER    DEFAULT NULL,
    p_skip_window_check IN VARCHAR2 DEFAULT 'N',
    p_skip_email_verification IN VARCHAR2 DEFAULT 'N',
    p_id        OUT NUMBER
  );

  PROCEDURE update_participant(
    p_id     IN NUMBER,
    p_status IN VARCHAR2  DEFAULT NULL,
    p_active IN VARCHAR2  DEFAULT NULL
  );

  PROCEDURE submit_audio(
    p_id                 IN  NUMBER,
    p_audio_url          IN  VARCHAR2,
    p_audio_submitted_on OUT TIMESTAMP WITH TIME ZONE
  );

  PROCEDURE delete_participant(p_id IN NUMBER);

  PROCEDURE list_by_event(p_event_id IN NUMBER, p_result OUT SYS_REFCURSOR);

  PROCEDURE get_participant(p_id IN NUMBER, p_result OUT SYS_REFCURSOR);

  PROCEDURE list_by_user(p_user_id IN NUMBER, p_result OUT SYS_REFCURSOR);

  PROCEDURE replace_youtube_tracks (
    p_participant_id IN gcode_event_participants.id%TYPE,
    p_items          IN CLOB
  );

  PROCEDURE replace_team_members (
    p_participant_id IN gcode_event_participants.id%TYPE,
    p_items          IN CLOB
  );

END gcode_event_participants_api;
/


CREATE OR REPLACE
PACKAGE BODY gcode_event_participants_api AS

PROCEDURE create_participant(
    p_event_id  IN  NUMBER,
    p_email     IN  VARCHAR2  DEFAULT NULL,
    p_full_name IN  VARCHAR2  DEFAULT NULL,
    p_quantity  IN  NUMBER    DEFAULT 1,
    p_status    IN  VARCHAR2  DEFAULT 'PENDING',
    p_active    IN  VARCHAR2  DEFAULT 'Y',
    p_category  IN  VARCHAR2  DEFAULT 'ATTENDEE',
    p_phone     IN  VARCHAR2  DEFAULT NULL,
    p_user_id   IN  NUMBER    DEFAULT NULL,
    p_skip_window_check IN VARCHAR2 DEFAULT 'N',
    p_skip_email_verification IN VARCHAR2 DEFAULT 'N',
    p_id        OUT NUMBER
  ) IS
    v_user_id                 gcode_users.user_id%TYPE;
    v_resolved_email          gcode_users.email%TYPE;
    v_resolved_full_name      gcode_users.full_name%TYPE;
    v_phone                   gcode_users.phone%TYPE;
    v_is_phone_verified       gcode_users.is_phone_verified%TYPE;
    v_phone_verified_pending  gcode_pending_users.is_phone_verified%TYPE;
    v_quantity                NUMBER := NVL(p_quantity, 1);
    v_category                VARCHAR2(20) := NVL(p_category, 'ATTENDEE');
    v_max_attendees           events.max_attendees%TYPE;
    v_max_per_reg             events.max_tickets_per_registration%TYPE;
    v_participant_max_per_reg events.participant_max_tickets_per_registration%TYPE;
    v_effective_max_per_reg   NUMBER;
    v_participant_capacity    events.participant_capacity%TYPE;
    v_reg_start               events.registration_start%TYPE;
    v_reg_deadline             events.registration_deadline%TYPE;
    v_participant_reg_start   events.participant_registration_start%TYPE;
    v_participant_reg_deadline events.participant_registration_deadline%TYPE;
    v_effective_reg_start     events.registration_start%TYPE;
    v_effective_reg_deadline  events.registration_deadline%TYPE;
    v_title                   events.title%TYPE;
    v_start_date              events.start_date%TYPE;
    v_booked                  NUMBER;
    v_verified                NUMBER;
    v_existing_id              GCODE_EVENT_PARTICIPANTS.id%TYPE;
  BEGIN
    -- A person already actively registered for this event (matched by
    -- user_id or verified email — phone is excluded since it isn't a
    -- verified identity key) can't register again. Checked first, before
    -- any capacity/window validation or gcode_users find-or-create, so a
    -- repeat attempt neither wastes a capacity slot check nor creates a
    -- stray user row.
    SELECT MIN(ep.id)
      INTO v_existing_id
      FROM GCODE_EVENT_PARTICIPANTS ep
      JOIN gcode_users u ON u.user_id = ep.user_id
     WHERE ep.event_id = p_event_id
       AND ep.active   = 'Y'
       AND ep.status  <> 'CANCELLED'
       AND (
             (p_user_id IS NOT NULL AND u.user_id = p_user_id)
          OR (p_email   IS NOT NULL AND u.email   = p_email)
           );

    IF v_existing_id IS NOT NULL THEN
      -- Silent no-op success: the ORDS handler for the free-registration
      -- endpoint (POST /events/{id}/participants) does its own duplicate
      -- pre-check and messaging via HTP.print before ever calling this
      -- procedure — this is only a safety net for callers that skip that
      -- pre-check, e.g. GCODE_PAYMENTS_API.finalize_order on the paid path.
      p_id := v_existing_id;
      RETURN;
    END IF;

    IF v_quantity < 1 THEN
      RAISE_APPLICATION_ERROR(-20002, 'Ticket quantity must be at least 1.');
    END IF;

    SELECT max_attendees, max_tickets_per_registration, participant_capacity,
           participant_max_tickets_per_registration,
           registration_start, registration_deadline,
           participant_registration_start, participant_registration_deadline,
           title, start_date
    INTO   v_max_attendees, v_max_per_reg, v_participant_capacity,
           v_participant_max_per_reg,
           v_reg_start, v_reg_deadline,
           v_participant_reg_start, v_participant_reg_deadline,
           v_title, v_start_date
    FROM   events
    WHERE  id = p_event_id;

    v_effective_max_per_reg := CASE WHEN v_category = 'PARTICIPANT'
                                    THEN v_participant_max_per_reg
                                    ELSE v_max_per_reg END;

    IF v_effective_max_per_reg IS NOT NULL AND v_quantity > v_effective_max_per_reg THEN
      RAISE_APPLICATION_ERROR(-20001,
        'Maximum ' || v_effective_max_per_reg || ' ticket(s) allowed per registration.');
    END IF;

    IF NVL(p_skip_window_check, 'N') != 'Y' AND p_user_id IS NULL THEN
      v_effective_reg_start    := CASE WHEN v_category = 'PARTICIPANT'
                                       THEN v_participant_reg_start ELSE v_reg_start END;
      v_effective_reg_deadline := CASE WHEN v_category = 'PARTICIPANT'
                                       THEN v_participant_reg_deadline ELSE v_reg_deadline END;

      IF v_effective_reg_start IS NOT NULL AND SYSTIMESTAMP < v_effective_reg_start THEN
        RAISE_APPLICATION_ERROR(-20004, 'Registration has not opened yet.');
      END IF;
      IF v_effective_reg_deadline IS NOT NULL AND SYSTIMESTAMP > v_effective_reg_deadline THEN
        RAISE_APPLICATION_ERROR(-20004, 'Registration is closed.');
      END IF;
    END IF;

    IF v_category = 'PARTICIPANT' THEN
      IF v_participant_capacity IS NOT NULL THEN
        SELECT NVL(SUM(quantity), 0) INTO v_booked
        FROM GCODE_EVENT_PARTICIPANTS
        WHERE event_id = p_event_id AND active = 'Y' AND category = 'PARTICIPANT';

        IF v_booked + v_quantity > v_participant_capacity THEN
          RAISE_APPLICATION_ERROR(-20001,
            'Only ' || (v_participant_capacity - v_booked) || ' spot(s) left for this event.');
        END IF;
      END IF;
    ELSE
      IF v_max_attendees IS NOT NULL THEN
        SELECT NVL(SUM(quantity), 0) INTO v_booked
        FROM GCODE_EVENT_PARTICIPANTS
        WHERE event_id = p_event_id AND active = 'Y' AND category = 'ATTENDEE';

        IF v_booked + v_quantity > v_max_attendees THEN
          RAISE_APPLICATION_ERROR(-20001,
            'Only ' || (v_max_attendees - v_booked) || ' ticket(s) left for this event.');
        END IF;
      END IF;
    END IF;

    IF p_user_id IS NOT NULL THEN
      SELECT user_id, email, full_name, phone, is_phone_verified
      INTO   v_user_id, v_resolved_email, v_resolved_full_name, v_phone, v_is_phone_verified
      FROM   gcode_users
      WHERE  user_id = p_user_id;
    ELSE
      BEGIN
        SELECT user_id, email, full_name, phone, is_phone_verified
        INTO   v_user_id, v_resolved_email, v_resolved_full_name, v_phone, v_is_phone_verified
        FROM   gcode_users WHERE email = p_email;
      EXCEPTION WHEN NO_DATA_FOUND THEN
        SELECT COUNT(*) INTO v_verified
        FROM gcode_pending_users
        WHERE email = p_email AND is_verified = 'Y';

        IF v_verified = 0 AND NVL(p_skip_email_verification, 'N') != 'Y' THEN
          RAISE_APPLICATION_ERROR(-20003,
            'Email not verified. Please verify your email before registering.');
        END IF;

        BEGIN
          SELECT is_phone_verified INTO v_phone_verified_pending
          FROM gcode_pending_users WHERE email = p_email;
        EXCEPTION WHEN NO_DATA_FOUND THEN
          v_phone_verified_pending := 'N';
        END;

        BEGIN
          INSERT INTO gcode_users (email, full_name, phone, is_phone_verified)
          VALUES (p_email, p_full_name, p_phone, NVL(v_phone_verified_pending, 'N'))
          RETURNING user_id, email, full_name INTO v_user_id, v_resolved_email, v_resolved_full_name;
          v_phone := p_phone;
          v_is_phone_verified := NVL(v_phone_verified_pending, 'N');
        EXCEPTION WHEN DUP_VAL_ON_INDEX THEN
          SELECT user_id, email, full_name, phone, is_phone_verified
          INTO   v_user_id, v_resolved_email, v_resolved_full_name, v_phone, v_is_phone_verified
          FROM   gcode_users WHERE email = p_email;
        END;

        DELETE FROM gcode_pending_users WHERE email = p_email;
      END;
    END IF;

    INSERT INTO GCODE_EVENT_PARTICIPANTS (
      event_id, user_id, user_name, quantity, applied_on, status, active,
      category, created_by, created_on, updated_by, updated_on
    ) VALUES (
      p_event_id, v_user_id, v_resolved_full_name, v_quantity, SYSTIMESTAMP,
      NVL(p_status, 'PENDING'), NVL(p_active, 'Y'),
      v_category,
      USER, SYSTIMESTAMP, USER, SYSTIMESTAMP
    ) RETURNING id INTO p_id;

    COMMIT;

    BEGIN
      GCODE_EMAIL_API.send_confirmation_email(
        p_email          => v_resolved_email,
        p_full_name      => v_resolved_full_name,
        p_event_id       => p_event_id,
        p_participant_id => p_id,
        p_quantity       => v_quantity,
        p_category       => v_category
      );
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;

    -- WhatsApp thank-you is Participant-only — the frontend's opt-in
    -- checkbox is only ever shown on that path, so is_phone_verified should
    -- never be 'Y' for an Attendee, but the category check is kept explicit
    -- here rather than relying on that alone.
    IF v_is_phone_verified = 'Y' AND v_phone IS NOT NULL AND v_category = 'PARTICIPANT' THEN
      BEGIN
        GCODE_WHATSAPP_API.send_event_update(
          p_phone           => v_phone,
          p_full_name       => v_resolved_full_name,
          p_message         => 'Thanks for registering as a Participant for ' || v_title || '! We''re excited to have you.',
          p_banner_media_id => GCODE_WHATSAPP_API.get_or_upload_event_media(p_event_id),
          p_template_name   => 'participant_registration_thanks'
        );
      EXCEPTION
        WHEN OTHERS THEN NULL;
      END;
    END IF;
  END create_participant;


  PROCEDURE update_participant(
    p_id     IN NUMBER,
    p_status IN VARCHAR2  DEFAULT NULL,
    p_active IN VARCHAR2  DEFAULT NULL
  ) IS
  BEGIN
    UPDATE GCODE_EVENT_PARTICIPANTS SET
      status     = NVL(p_status, status),
      active     = NVL(p_active, active),
      updated_by = USER,
      updated_on = SYSTIMESTAMP
    WHERE id = p_id;
    COMMIT;
  END update_participant;

 PROCEDURE submit_audio(
    p_id                 IN  NUMBER,
    p_audio_url          IN  VARCHAR2,
    p_audio_submitted_on OUT TIMESTAMP WITH TIME ZONE
  ) IS
    v_email               gcode_users.email%TYPE;
    v_phone               gcode_users.phone%TYPE;
    v_is_phone_verified   gcode_users.is_phone_verified%TYPE;
    v_full_name           GCODE_EVENT_PARTICIPANTS.user_name%TYPE;
    v_event_id            GCODE_EVENT_PARTICIPANTS.event_id%TYPE;
    v_event_title         events.title%TYPE;
    v_user_id             GCODE_EVENT_PARTICIPANTS.user_id%TYPE;
    v_applied_on          GCODE_EVENT_PARTICIPANTS.applied_on%TYPE;
    v_reg_deadline        EVENTS.participant_registration_deadline%TYPE;
    v_submission_deadline TIMESTAMP WITH TIME ZONE;
  BEGIN
    BEGIN
      SELECT p.event_id, p.applied_on
        INTO v_event_id, v_applied_on
        FROM gcode_event_participants p
       WHERE p.id = p_id;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20005, 'Participant not found.');
    END;

    -- Only the first submission is deadline-gated — once submitted, the
    -- participant can keep replacing it, matching the frontend's
    -- isDisqualified rule (past deadline AND no submission yet).

      SELECT e.participant_registration_deadline
        INTO v_reg_deadline
        FROM events e
       WHERE e.id = v_event_id;

      v_submission_deadline :=
        NVL(v_reg_deadline, v_applied_on) + INTERVAL '24' HOUR;

      IF SYSTIMESTAMP > v_submission_deadline THEN
        RAISE_APPLICATION_ERROR(-20011, 'Submission window has closed.');
      END IF;


    UPDATE gcode_event_participants
    SET audio_submission_url = p_audio_url,
        audio_submitted_on   = SYSTIMESTAMP
    WHERE id = p_id
    RETURNING audio_submitted_on, user_name, event_id, user_id
      INTO p_audio_submitted_on, v_full_name, v_event_id, v_user_id;

    IF SQL%ROWCOUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20005, 'Participant not found.');
    END IF;

    COMMIT;

    BEGIN
      SELECT email, phone, is_phone_verified
      INTO   v_email, v_phone, v_is_phone_verified
      FROM   gcode_users WHERE user_id = v_user_id;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      v_email := NULL;
      v_phone := NULL;
      v_is_phone_verified := 'N';
    END;

    IF v_email IS NOT NULL THEN
      BEGIN
        GCODE_EMAIL_API.send_submission_received_email(v_email, v_full_name, v_event_id, p_id, p_audio_url);
      EXCEPTION WHEN OTHERS THEN
        NULL;
      END;
    END IF;

    IF v_is_phone_verified = 'Y' AND v_phone IS NOT NULL THEN
      BEGIN
        SELECT title INTO v_event_title FROM events WHERE id = v_event_id;
        GCODE_WHATSAPP_API.send_submission_received(v_phone, v_full_name, v_event_title);
      EXCEPTION WHEN OTHERS THEN
        NULL;
      END;
    END IF;
  END submit_audio;



  PROCEDURE delete_participant(p_id IN NUMBER) IS
  BEGIN
    -- Soft delete — keeps score/decision/payment history intact for
    -- tracking instead of hard-deleting through NO ACTION FKs. STATUS =
    -- 'CANCELLED' is already the recognized "not actively registered"
    -- marker elsewhere (create_participant's own duplicate-registration
    -- check already excludes it), so this reuses that convention rather
    -- than inventing a new one.
    UPDATE GCODE_EVENT_PARTICIPANTS
    SET STATUS = 'CANCELLED',
        ACTIVE = 'N',
        UPDATED_BY = USER,
        UPDATED_ON = SYSTIMESTAMP
    WHERE ID = p_id;
    COMMIT;
  END delete_participant;


  PROCEDURE list_by_event(p_event_id IN NUMBER, p_result OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_result FOR
      SELECT p.id            AS "id",
             p.event_id       AS "event_id",
             TO_CHAR(p.user_id)        AS "user_id",
             p.user_name      AS "user_name",
             p.quantity       AS "quantity",
             p.status         AS "status",
             p.active         AS "active",
             p.applied_on     AS "applied_on",
             gu.email         AS "email",
             gu.phone         AS "phone",
             gr.role_name     AS "role_name",
             p.category       AS "category",
             p.audio_submission_url AS "audio_submission_url",
             p.audio_submitted_on   AS "audio_submitted_on"
      FROM GCODE_EVENT_PARTICIPANTS p
      LEFT JOIN gcode_users gu ON gu.user_id = p.user_id
      LEFT JOIN gcode_roles gr ON gr.role_id = gu.role_id
      WHERE p.event_id = p_event_id
      ORDER BY p.applied_on DESC;
  END list_by_event;

  PROCEDURE get_participant(p_id IN NUMBER, p_result OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_result FOR
      SELECT p.id            AS "id",
             p.event_id       AS "event_id",
             TO_CHAR(p.user_id)     AS "user_id",
             p.user_name      AS "user_name",
             p.quantity       AS "quantity",
             p.status         AS "status",
             p.active         AS "active",
             p.applied_on     AS "applied_on",
             gu.email         AS "email",
             gu.phone         AS "phone",
             gr.role_name     AS "role_name",
             p.category       AS "category",
             p.audio_submission_url AS "audio_submission_url",
             p.audio_submitted_on   AS "audio_submitted_on"
      FROM GCODE_EVENT_PARTICIPANTS p
      LEFT JOIN gcode_users gu ON gu.user_id = p.user_id
      LEFT JOIN gcode_roles gr ON gr.role_id = gu.role_id
      WHERE p.id = p_id;
  END get_participant;

  PROCEDURE list_by_user(p_user_id IN NUMBER, p_result OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_result FOR
      SELECT p.id               AS "participant_id",
             p.event_id         AS "event_id",
             e.title            AS "event_name",
             e.event_type_id    AS "event_type_id",
             e.mode_of_event_id AS "mode_of_event_id",
             e.status_id        AS "status_id",
             e.start_date       AS "start_date",
             e.city             AS "city",
             e.venue_address    AS "address",
             e.ticket_price     AS "ticket_price",
             e.participant_price AS "participant_price",
             e.cover_image_url  AS "cover_image_url",
             p.quantity         AS "quantity",
             p.status           AS "status",
             p.active            AS "active",
             p.applied_on        AS "applied_on",
             p.category           AS "category"
      FROM GCODE_EVENT_PARTICIPANTS p
      JOIN events e ON e.id = p.event_id
      WHERE p.user_id = p_user_id
      ORDER BY e.start_date DESC NULLS LAST;
  END list_by_user;

  PROCEDURE replace_youtube_tracks (p_participant_id IN gcode_event_participants.id%TYPE, p_items IN CLOB) IS
  BEGIN
    DELETE FROM participant_youtube_tracks WHERE participant_id = p_participant_id;
    INSERT INTO participant_youtube_tracks (participant_id, track_name, youtube_url, sort_order)
    SELECT p_participant_id, j.track_name, j.youtube_url, j.sort_order
    FROM JSON_TABLE(p_items, '$[*]' COLUMNS (
      track_name  VARCHAR2(200)  PATH '$.trackName',
      youtube_url VARCHAR2(1000) PATH '$.youtubeUrl',
      sort_order  NUMBER         PATH '$.sortOrder'
    )) j;
  END replace_youtube_tracks;

  PROCEDURE replace_team_members (p_participant_id IN gcode_event_participants.id%TYPE, p_items IN CLOB) IS
  BEGIN
    DELETE FROM participant_team_members WHERE participant_id = p_participant_id;
    INSERT INTO participant_team_members (participant_id, member_name, sort_order)
    SELECT p_participant_id, j.member_name, j.sort_order
    FROM JSON_TABLE(p_items, '$[*]' COLUMNS (
      member_name VARCHAR2(200) PATH '$.memberName',
      sort_order  NUMBER        PATH '$.sortOrder'
    )) j;
  END replace_team_members;

END gcode_event_participants_api;
/


-- ----------------------------------------------------------------------------
-- 4. ORDS: gcode.events.v1 -- update existing POST / and PUT :id handlers
--    (adds the 4 new binds to each; everything else on these two handlers
--    is unchanged from what's already live)
-- ----------------------------------------------------------------------------

-- Generated by ORDS REST Data Services 26.2.1.r1901402
-- Schema: WKSP_GCODE2  Date: Sat Aug 29 05:05:09 2026

-- Module: gcode.events.v1
-- Template pattern: /

BEGIN
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'gcode.events.v1',
      p_pattern        => '/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gcode.events.v1',
      p_pattern        => '/',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'      SELECT e.id, e.title AS event_name, e.event_type_id, e.mode_of_event_id,
             e.status_id, e.city, e.venue_address AS address, e.start_date, e.end_date,
             e.max_attendees, e.ticket_price, e.is_featured,
             e.cover_image_url, e.banner_image_url, e.participation_link,
             (SELECT NVL(SUM(gep.quantity),0) FROM gcode_event_participants gep
              WHERE gep.event_id = e.id AND gep.active = ''Y'') AS registered_count
      FROM events e
      WHERE (:type_id     IS NULL OR e.event_type_id    = :type_id)
        AND (:mode_id     IS NULL OR e.mode_of_event_id = :mode_id)
        AND (:status_id   IS NULL OR e.status_id        = :status_id)
        AND (:is_featured IS NULL OR e.is_featured      = :is_featured)
        AND (:search      IS NULL OR UPPER(e.title) LIKE ''%''||UPPER(:search)||''%'')
        AND e.id != 81 AND e.id != 61
      ORDER BY e.start_date DESC NULLS LAST
    ');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gcode.events.v1',
      p_pattern        => '/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'      DECLARE l_id NUMBER;
      BEGIN
        gcode_events_api.create_event(
          p_title => :title, p_event_type_id => :event_type_id,
          p_mode_of_event_id => :mode_of_event_id, p_status_id => :status_id,
          p_summary => :summary, p_description => :description,
          p_start_date => :start_date, p_end_date => :end_date,
          p_registration_deadline => :registration_deadline, p_city => :city,
          p_venue_address => :venue_address, p_participation_link => :participation_link,
          p_max_attendees => :max_attendees, p_ticket_price => :ticket_price,
          p_is_featured => :is_featured, p_certificate_offered => :certificate_offered,
          p_cover_image_url => :cover_image_url, p_banner_image_url => :banner_image_url,
          p_is_external => :is_external, p_external_url => :external_url,
          p_created_by => :created_by, p_organizer_id => :organizer_id,
          p_max_tickets_per_registration => :max_tickets_per_registration,
       ' || '   p_terms => :terms, p_eligibility => :eligibility,
          p_attendee_label                   => :attendee_label,
          p_attendee_description             => :attendee_description,
          p_attendee_registration_enabled    => :attendee_registration_enabled,
          p_participant_registration_enabled => :participant_registration_enabled,
          p_participant_label                => :participant_label,
          p_participant_description          => :participant_description,
          p_participant_price                => :participant_price,
          p_participant_capacity             => :participant_capacity,
          p_participant_max_tickets_per_registration => :participant_max_tickets_per_registration,
          p_registration_start => :registration_start,
          p_participant_registration_start => :participant_registration_start,
          p_participant_registration_deadline => :participant_registration_deadline,
          p_duration_text => :duration_text,
          p_audio_recording_enabled => :audio_recording_enabled,
          p_age_category_requirement => :age_category_requirement,
          p_track_submission_enabled => :track_submission_enabled,
          p_member_names_enabled => :member_names_enabled,
          p_i' || 'd => l_id);
        APEX_JSON.open_object;
        APEX_JSON.write(''id'', l_id);
        APEX_JSON.close_object;
        :status_code := 201;
      END;
    ');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

-- Generated by ORDS REST Data Services 26.2.1.r1901402
-- Schema: WKSP_GCODE2  Date: Sat Aug 29 05:05:09 2026

-- Module: gcode.events.v1
-- Template pattern: :id

BEGIN
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'gcode.events.v1',
      p_pattern        => ':id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gcode.events.v1',
      p_pattern        => ':id',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'      BEGIN
        gcode_events_api.update_event(
          p_id => :id, p_title => :title, p_event_type_id => :event_type_id,
          p_mode_of_event_id => :mode_of_event_id, p_status_id => :status_id,
          p_summary => :summary, p_description => :description,
          p_start_date => :start_date, p_end_date => :end_date,
          p_registration_deadline => :registration_deadline, p_city => :city,
          p_venue_address => :venue_address, p_participation_link => :participation_link,
          p_max_attendees => :max_attendees, p_ticket_price => :ticket_price,
          p_is_featured => :is_featured, p_certificate_offered => :certificate_offered,
          p_cover_image_url => :cover_image_url, p_banner_image_url => :banner_image_url,
          p_is_external => :is_external, p_external_url => :external_url,
          p_updated_by => :updated_by, p_organizer_id => :organizer_id,
          p_max_tickets_per_registration => :max_tickets_per_registration,
          p_terms => ' || ':terms, p_eligibility => :eligibility,
          p_attendee_label => :attendee_label,
          p_attendee_description => :attendee_description,
          p_attendee_registration_enabled    => :attendee_registration_enabled,
          p_participant_registration_enabled => :participant_registration_enabled,
          p_participant_label                => :participant_label,
          p_participant_description          => :participant_description,
          p_participant_price                => :participant_price,
          p_participant_capacity             => :participant_capacity,
          p_participant_max_tickets_per_registration => :participant_max_tickets_per_registration,
          p_registration_start => :registration_start,
          p_participant_registration_start => :participant_registration_start,
          p_participant_registration_deadline => :participant_registration_deadline,
          p_duration_text => :duration_text,
          p_rating_mode => :rating_mode,
          p_audio_recording_enabled => :audio_recording_enabled,
          p_age_category_requirement => :age_category_requirement,
          p_track_submission_enabled => :track_submission_enabled,
          p_member_names_enabled => :member_names_enabled);
     ' || ' END;
    ');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gcode.events.v1',
      p_pattern        => ':id',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'      DECLARE l_cur SYS_REFCURSOR;
      BEGIN
        gcode_events_api.get_event(p_id => :id, p_result => l_cur);
        APEX_JSON.open_object; APEX_JSON.write(''items'', l_cur); APEX_JSON.close_object;
      END;
    ');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gcode.events.v1',
      p_pattern        => ':id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'BEGIN gcode_events_api.delete_event(p_id => :id); END;');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

-- ----------------------------------------------------------------------------
-- 5. ORDS: gcode.participants.v1 -- new routes
-- ----------------------------------------------------------------------------

-- Generated by ORDS REST Data Services 26.2.1.r1901402
-- Schema: WKSP_GCODE2  Date: Thu Sep 03 2026

-- Module: gcode.participants.v1
-- Template pattern: :id/youtube-tracks

BEGIN
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'gcode.participants.v1',
      p_pattern        => ':id/youtube-tracks',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gcode.participants.v1',
      p_pattern        => ':id/youtube-tracks',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'
      SELECT track_name, youtube_url, sort_order
      FROM participant_youtube_tracks
      WHERE participant_id = :id
      ORDER BY sort_order
    ');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gcode.participants.v1',
      p_pattern        => ':id/youtube-tracks',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'BEGIN gcode_event_participants_api.replace_youtube_tracks(p_participant_id => :id, p_items => :body_text); END;');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

-- Generated by ORDS REST Data Services 26.2.1.r1901402
-- Schema: WKSP_GCODE2  Date: Thu Sep 03 2026

-- Module: gcode.participants.v1
-- Template pattern: :id/team-members

BEGIN
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'gcode.participants.v1',
      p_pattern        => ':id/team-members',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gcode.participants.v1',
      p_pattern        => ':id/team-members',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'
      SELECT member_name, sort_order
      FROM participant_team_members
      WHERE participant_id = :id
      ORDER BY sort_order
    ');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gcode.participants.v1',
      p_pattern        => ':id/team-members',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'BEGIN gcode_event_participants_api.replace_team_members(p_participant_id => :id, p_items => :body_text); END;');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

-- ============================================================================
-- Verification (run after the above completes with no errors):
--
--   SELECT column_name FROM user_tab_columns WHERE table_name='EVENTS'
--     AND column_name IN ('AUDIO_RECORDING_ENABLED','AGE_CATEGORY_REQUIREMENT',
--                          'TRACK_SUBMISSION_ENABLED','MEMBER_NAMES_ENABLED');
--   -- expect 4 rows
--
--   SELECT object_type, status FROM user_objects
--     WHERE object_name IN ('GCODE_EVENTS_API','GCODE_EVENT_PARTICIPANTS_API');
--   -- expect all VALID
--
-- Then, from the app (or curl), against the PROD ORDS base URL:
--   POST /events/                          -- with audio_recording_enabled,
--                                              age_category_requirement,
--                                              track_submission_enabled,
--                                              member_names_enabled in the body
--   GET/POST /participants/:id/youtube-tracks
--   GET/POST /participants/:id/team-members
--
-- Only flip NEXT_PUBLIC_API_BASE_URL (or however prod deploy points at the
-- API) once those all come back clean.
-- ============================================================================
