-- EVENTS: audio recording gets its own individual audience setting,
-- replacing the page-wide switch an earlier draft of this feature tried
-- (never shipped) — no "both" combined value, one category at a time.
ALTER TABLE EVENTS ADD (
  AUDIO_RECORDING_APPLIES_TO VARCHAR2(20) DEFAULT 'PARTICIPANT' NOT NULL
);
ALTER TABLE EVENTS ADD CONSTRAINT CK_EVENTS_AUDIO_RECORDING_APPLIES_TO
  CHECK (AUDIO_RECORDING_APPLIES_TO IN ('ATTENDEE','PARTICIPANT'));

-- Organizer-authored custom questions (TEXT/RADIO/CHECKBOX). Each question
-- picks its own APPLIES_TO individually — same convention as audio above.
CREATE TABLE GCODE_EVENT_QUESTIONS (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EVENT_ID     NUMBER NOT NULL REFERENCES EVENTS (ID) ON DELETE CASCADE,
  PROMPT       VARCHAR2(500) NOT NULL,
  QUESTION_TYPE VARCHAR2(20) NOT NULL,
  IS_REQUIRED  NUMBER(1,0) DEFAULT 0 NOT NULL,
  APPLIES_TO   VARCHAR2(20) DEFAULT 'PARTICIPANT' NOT NULL,
  SORT_ORDER   NUMBER DEFAULT 0,
  CREATED_ON   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_GCODE_EVENT_QUESTIONS_TYPE CHECK (QUESTION_TYPE IN ('TEXT','RADIO','CHECKBOX')),
  CONSTRAINT CK_GCODE_EVENT_QUESTIONS_REQUIRED CHECK (IS_REQUIRED IN (0,1)),
  CONSTRAINT CK_GCODE_EVENT_QUESTIONS_APPLIES_TO CHECK (APPLIES_TO IN ('ATTENDEE','PARTICIPANT'))
);
CREATE INDEX IX_GCODE_EVENT_QUESTIONS_EVENT ON GCODE_EVENT_QUESTIONS (EVENT_ID);

-- One selectable answer for a RADIO/CHECKBOX question.
CREATE TABLE GCODE_EVENT_QUESTION_OPTIONS (
  ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  QUESTION_ID  NUMBER NOT NULL REFERENCES GCODE_EVENT_QUESTIONS (ID) ON DELETE CASCADE,
  OPTION_LABEL VARCHAR2(200) NOT NULL,
  SORT_ORDER   NUMBER DEFAULT 0
);
CREATE INDEX IX_GCODE_QUESTION_OPTIONS_QUESTION ON GCODE_EVENT_QUESTION_OPTIONS (QUESTION_ID);

-- Participant answers. One row per selected option for RADIO/CHECKBOX
-- (several rows, same question, for a multi-select CHECKBOX answer), or
-- one row with ANSWER_TEXT (OPTION_ID null) for TEXT.
CREATE TABLE PARTICIPANT_QUESTION_ANSWERS (
  ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PARTICIPANT_ID NUMBER NOT NULL REFERENCES GCODE_EVENT_PARTICIPANTS (ID) ON DELETE CASCADE,
  QUESTION_ID    NUMBER NOT NULL REFERENCES GCODE_EVENT_QUESTIONS (ID) ON DELETE CASCADE,
  OPTION_ID      NUMBER REFERENCES GCODE_EVENT_QUESTION_OPTIONS (ID) ON DELETE CASCADE,
  ANSWER_TEXT    VARCHAR2(1000)
);
CREATE INDEX IX_QUESTION_ANSWERS_PARTICIPANT ON PARTICIPANT_QUESTION_ANSWERS (PARTICIPANT_ID);

-- Note: AGE_CATEGORY_REQUIREMENT / TRACK_SUBMISSION_ENABLED /
-- MEMBER_NAMES_ENABLED (docs/sql/additional-info/, shipped earlier) are
-- untouched by this migration — the frontend just stopped reading/writing
-- them, since custom questions supersede them. Existing events may still
-- carry that data; nothing here drops it.
